services:
  web:
    container_name: portfolio-web
    image: ${DOCKER_IMAGE:-sierrapablo/portfolio-web:latest}
    expose:
      - "4321"
    restart: unless-stopped
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external: true
